services:
  db:
    image: bitnami/postgresql:latest
    container_name: brevly_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly_links
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - server
      - db

  server:
    container_name: brevly_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3333'
    env_file:
      - server/.env
    volumes:
      - ./server:/usr/src/app
    command: npm start
    depends_on:
      - db
    networks:
      - server

volumes:
  db:

networks:
  server:
    driver: bridge
  db:
    driver: bridge
